# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created: Sat Apr 12 13:35:25 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ui(object):
    def setupUi(self, ui):
        ui.setObjectName(_fromUtf8("ui"))
        ui.resize(471, 235)
        self.gridLayout = QtGui.QGridLayout(ui)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButtonInvert = QtGui.QPushButton(ui)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonInvert.sizePolicy().hasHeightForWidth())
        self.pushButtonInvert.setSizePolicy(sizePolicy)
        self.pushButtonInvert.setObjectName(_fromUtf8("pushButtonInvert"))
        self.gridLayout.addWidget(self.pushButtonInvert, 7, 1, 1, 1)
        self.groupBoxParameters = QtGui.QGroupBox(ui)
        self.groupBoxParameters.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBoxParameters.setObjectName(_fromUtf8("groupBoxParameters"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBoxParameters)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_4 = QtGui.QLabel(self.groupBoxParameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 2, 1, 1)
        self.spinA = QtGui.QDoubleSpinBox(self.groupBoxParameters)
        self.spinA.setMinimumSize(QtCore.QSize(100, 0))
        self.spinA.setDecimals(8)
        self.spinA.setMinimum(-999999999.0)
        self.spinA.setMaximum(999999999.0)
        self.spinA.setSingleStep(0.1)
        self.spinA.setProperty("value", 1.0)
        self.spinA.setObjectName(_fromUtf8("spinA"))
        self.gridLayout_2.addWidget(self.spinA, 0, 1, 1, 1)
        self.spinTx = QtGui.QDoubleSpinBox(self.groupBoxParameters)
        self.spinTx.setMinimumSize(QtCore.QSize(100, 0))
        self.spinTx.setDecimals(8)
        self.spinTx.setMinimum(-999999999.0)
        self.spinTx.setMaximum(999999999.0)
        self.spinTx.setSingleStep(1.0)
        self.spinTx.setProperty("value", 0.0)
        self.spinTx.setObjectName(_fromUtf8("spinTx"))
        self.gridLayout_2.addWidget(self.spinTx, 0, 5, 1, 1)
        self.spinB = QtGui.QDoubleSpinBox(self.groupBoxParameters)
        self.spinB.setMinimumSize(QtCore.QSize(100, 0))
        self.spinB.setDecimals(8)
        self.spinB.setMinimum(-999999999.0)
        self.spinB.setMaximum(999999999.0)
        self.spinB.setSingleStep(0.1)
        self.spinB.setProperty("value", 0.0)
        self.spinB.setObjectName(_fromUtf8("spinB"))
        self.gridLayout_2.addWidget(self.spinB, 0, 3, 1, 1)
        self.spinC = QtGui.QDoubleSpinBox(self.groupBoxParameters)
        self.spinC.setMinimumSize(QtCore.QSize(100, 0))
        self.spinC.setDecimals(8)
        self.spinC.setMinimum(-999999999.0)
        self.spinC.setMaximum(999999999.0)
        self.spinC.setSingleStep(0.1)
        self.spinC.setProperty("value", 0.0)
        self.spinC.setObjectName(_fromUtf8("spinC"))
        self.gridLayout_2.addWidget(self.spinC, 1, 1, 1, 1)
        self.spinD = QtGui.QDoubleSpinBox(self.groupBoxParameters)
        self.spinD.setMinimumSize(QtCore.QSize(100, 0))
        self.spinD.setDecimals(8)
        self.spinD.setMinimum(-999999999.0)
        self.spinD.setMaximum(999999999.0)
        self.spinD.setSingleStep(0.1)
        self.spinD.setProperty("value", 1.0)
        self.spinD.setObjectName(_fromUtf8("spinD"))
        self.gridLayout_2.addWidget(self.spinD, 1, 3, 1, 1)
        self.spinTy = QtGui.QDoubleSpinBox(self.groupBoxParameters)
        self.spinTy.setMinimumSize(QtCore.QSize(100, 0))
        self.spinTy.setDecimals(8)
        self.spinTy.setMinimum(-999999999.0)
        self.spinTy.setMaximum(999999999.0)
        self.spinTy.setSingleStep(1.0)
        self.spinTy.setProperty("value", 0.0)
        self.spinTy.setObjectName(_fromUtf8("spinTy"))
        self.gridLayout_2.addWidget(self.spinTy, 1, 5, 1, 1)
        self.label = QtGui.QLabel(self.groupBoxParameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBoxParameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBoxParameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBoxParameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 4, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBoxParameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 1, 4, 1, 1)
        self.gridLayout.addWidget(self.groupBoxParameters, 6, 0, 1, 5)
        self.radioButtonSelectedFeatures = QtGui.QRadioButton(ui)
        self.radioButtonSelectedFeatures.setChecked(True)
        self.radioButtonSelectedFeatures.setObjectName(_fromUtf8("radioButtonSelectedFeatures"))
        self.gridLayout.addWidget(self.radioButtonSelectedFeatures, 4, 0, 1, 4)
        self.radioButtonWholeLayer = QtGui.QRadioButton(ui)
        self.radioButtonWholeLayer.setChecked(False)
        self.radioButtonWholeLayer.setObjectName(_fromUtf8("radioButtonWholeLayer"))
        self.gridLayout.addWidget(self.radioButtonWholeLayer, 5, 0, 1, 4)
        self.pushButtonRun = QtGui.QPushButton(ui)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonRun.sizePolicy().hasHeightForWidth())
        self.pushButtonRun.setSizePolicy(sizePolicy)
        self.pushButtonRun.setObjectName(_fromUtf8("pushButtonRun"))
        self.gridLayout.addWidget(self.pushButtonRun, 7, 0, 1, 1)
        self.labelLayer = QtGui.QLabel(ui)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLayer.sizePolicy().hasHeightForWidth())
        self.labelLayer.setSizePolicy(sizePolicy)
        self.labelLayer.setObjectName(_fromUtf8("labelLayer"))
        self.gridLayout.addWidget(self.labelLayer, 2, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 7, 2, 1, 1)
        self.pushButtonClose = QtGui.QPushButton(ui)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonClose.sizePolicy().hasHeightForWidth())
        self.pushButtonClose.setSizePolicy(sizePolicy)
        self.pushButtonClose.setObjectName(_fromUtf8("pushButtonClose"))
        self.gridLayout.addWidget(self.pushButtonClose, 7, 3, 1, 2)
        self.comboBoxLayer = QtGui.QComboBox(ui)
        self.comboBoxLayer.setObjectName(_fromUtf8("comboBoxLayer"))
        self.gridLayout.addWidget(self.comboBoxLayer, 2, 1, 1, 4)

        self.retranslateUi(ui)
        QtCore.QMetaObject.connectSlotsByName(ui)
        ui.setTabOrder(self.comboBoxLayer, self.radioButtonSelectedFeatures)
        ui.setTabOrder(self.radioButtonSelectedFeatures, self.radioButtonWholeLayer)
        ui.setTabOrder(self.radioButtonWholeLayer, self.spinA)
        ui.setTabOrder(self.spinA, self.spinB)
        ui.setTabOrder(self.spinB, self.spinC)
        ui.setTabOrder(self.spinC, self.spinD)
        ui.setTabOrder(self.spinD, self.spinTx)
        ui.setTabOrder(self.spinTx, self.spinTy)
        ui.setTabOrder(self.spinTy, self.pushButtonRun)
        ui.setTabOrder(self.pushButtonRun, self.pushButtonInvert)
        ui.setTabOrder(self.pushButtonInvert, self.pushButtonClose)

    def retranslateUi(self, ui):
        ui.setWindowTitle(_translate("ui", "Vector Affine Transformation", None))
        self.pushButtonInvert.setText(_translate("ui", "Invert Matrix", None))
        self.groupBoxParameters.setTitle(_translate("ui", "Transformation Matrix", None))
        self.label_4.setText(_translate("ui", "x +", None))
        self.label.setText(_translate("ui", "x\'=", None))
        self.label_2.setText(_translate("ui", "y\'=", None))
        self.label_3.setText(_translate("ui", "x +", None))
        self.label_5.setText(_translate("ui", "y +", None))
        self.label_6.setText(_translate("ui", "y +", None))
        self.radioButtonSelectedFeatures.setText(_translate("ui", "Selected features", None))
        self.radioButtonWholeLayer.setText(_translate("ui", "Whole layer", None))
        self.pushButtonRun.setText(_translate("ui", "Transform", None))
        self.labelLayer.setText(_translate("ui", "Layer:", None))
        self.pushButtonClose.setText(_translate("ui", "Close", None))

